# This file was generated by the CI/CD Wizard version 1.0.375.
# See the user guide for information on how to customize and use this file.

#-start from a prepared docker-image with a debian-distro from hub.docker.com
FROM debian:buster-slim

ENV DEBIAN_FRONTEND noninteractive



#-install addOn-tools needed into the preloaded debian-image
USER root
RUN dpkg --add-architecture i386 \
 && apt-get update -yq \
 && apt-get install -yq --no-install-recommends \
    ca-certificates \
    curl \
    make \
    unzip \
    procps \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*



# Download and install MPLAB X IDE version 5.55
ENV MPLABX_VERSION 5.50

RUN curl -fSL -A "Mozilla/4.0" -o /tmp/mplabx-installer.tar \
         "https://ww1.microchip.com/downloads/en/DeviceDoc/MPLABX-v${MPLABX_VERSION}-linux-installer.tar" \
 && tar xf /tmp/mplabx-installer.tar -C /tmp/ && rm /tmp/mplabx-installer.tar  \
 && USER=root ./tmp/MPLABX-v${MPLABX_VERSION}-linux-installer.sh --nox11 \
    -- --unattendedmodeui none --mode unattended \
 && rm ./tmp/MPLABX-v${MPLABX_VERSION}-linux-installer.sh \
 && rm -rf /opt/microchip/mplabx/v${MPLABX_VERSION}/packs/Microchip/*_DFP \
 && rm -rf /opt/microchip/mplabx/v${MPLABX_VERSION}/mplab_platform/browser-lib
ENV PATH /opt/microchip/mplabx/v${MPLABX_VERSION}/mplab_platform/bin:$PATH
ENV PATH /opt/microchip/mplabx/v${MPLABX_VERSION}/mplab_platform/mplab_ipe:$PATH




# Install MPLAB XC network license
RUN /opt/microchip/mplabx/v${MPLABX_VERSION}/mplab_platform/bin/xclm -netfile 5053 'licenses.microchip.com'; exit 0

# Download and install toolchain
ENV TOOLCHAIN xc32
ENV TOOLCHAIN_VERSION 2.50
RUN curl -fSL -A "Mozilla/4.0" -o /tmp/${TOOLCHAIN}.run \
    "https://ww1.microchip.com/downloads/en/DeviceDoc/${TOOLCHAIN}-v${TOOLCHAIN_VERSION}-full-install-linux-installer.run" \
 && chmod a+x /tmp/${TOOLCHAIN}.run \
 && /tmp/${TOOLCHAIN}.run --mode unattended --unattendedmodeui none \
    --netservername localhost --LicenseType NetworkMode \
 && rm /tmp/${TOOLCHAIN}.run
ENV PATH /opt/microchip/${TOOLCHAIN}/v${TOOLCHAIN_VERSION}/bin:$PATH


# DFPs needed for samd21xplp configuration
# Download and install Microchip.SAMD21_DFP.3.6.133
RUN curl -fSL -A "Mozilla/4.0" -o /tmp/tmp-pack.atpack \
         "https://packs.download.microchip.com/Microchip.SAMD21_DFP.3.5.132.atpack" \
 && mkdir -p /opt/microchip/mplabx/v${MPLABX_VERSION}/packs/SAMD21_DFP/3.6.133 \
 && unzip -o /tmp/tmp-pack.atpack -d /opt/microchip/mplabx/v${MPLABX_VERSION}/packs/SAMD21_DFP/3.6.133 \
 && rm /tmp/tmp-pack.atpack

# Download and install ARM.CMSIS.5.4.0
RUN curl -fSL -A "Mozilla/4.0" -o /tmp/tmp-pack.atpack \
         "https://packs.download.microchip.com/ARM.CMSIS.5.4.0.atpack" \
 && mkdir -p /opt/microchip/mplabx/v${MPLABX_VERSION}/packs/CMSIS/5.4.0 \
 && unzip -o /tmp/tmp-pack.atpack -d /opt/microchip/mplabx/v${MPLABX_VERSION}/packs/CMSIS/5.4.0 \
 && rm /tmp/tmp-pack.atpack



ENV BUILD_CONFIGURATION samd21xplp


#-install more addOn-tools into debian-image needed eg for doxygen or simulation
RUN apt-get update -yq \
 && apt-get install -yq --no-install-recommends \
    # Install packages required by doxygen
    doxygen \
    graphviz \
    texlive-fonts-recommended \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-latex-recommended \
    # Install packages required for testing
    nodejs \
    gcovr \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
